name: Deploy API

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [api]
  pull_request:
    branches: [api]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  # Deploy to Cloudflare Workers
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/api' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v6.0.1

      - name: Setup Bun and install dependencies
        uses: iamvikshan/.github/.github/actions/setup-node-bun@main

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: 2876f82607ce6dfdbd424448a00d69c6
          command: deploy --env production

  # Deploy API documentation to Bump.sh
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1.0.0
        with:
          doc: v1
          hub: amina
          token: ${{ secrets.BUMP_TOKEN }}
          file: docs/openapi.yaml

  # Check API diff on Bump.sh for pull requests
  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1.0.0
        with:
          doc: amina-api
          hub: amina
          token: ${{ secrets.BUMP_TOKEN }}
          file: docs/openapi.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
